add downloading resources code in tutorials
tinyms-ai/tinyms pull request #21
Opened 2021-03-03 10:45 UTC by lyd911

Codes for downloading resources (pics $ ckpt files) are added in tutorials, now users do not need to mannully download or create folders anymore.

Pic, ckpt file sources are all switched to obs.

2021-03-09 03:06 UTC, leonwanghui requested changes

2021-03-09 03:06 UTC, leonwanghui commented on tinyms/serving/client/client.py
> +        return (res_body['servables'])
Please remove `()` format

2021-03-09 03:21 UTC, lyd911 commented on tinyms/serving/client/client.py
> +        return (res_body['servables'])
done

2021-03-11 07:04 UTC, leonwanghui approved these changes
LGTM

2021-03-11 07:29 UTC, hellowaywewe approved these changes

2021-03-11 07:36 UTC, merged