Add community contributing document
tinyms-ai/tinyms pull request #40
Opened 2021-03-24 08:01 UTC by leonwanghui

Signed-off-by: leonwanghui <wanghui71leon@gmail.com>

2021-03-24 08:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tinyms-ai/tinyms?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tinyms-ai/tinyms?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tinyms-ai/tinyms?pullRequest=40) it.</sub>

2021-03-24 13:08 UTC, huxiaoman7 commented on docs/zh_CN/source/community/contributing.md
> +- 对于错误修复PR，请确保所有相关问题都已链接。
最后这里要不要加一个QQ群的二维码和小猫子的微信？让大家有问题或者不明白的地方也可以到群里交流。

2021-03-24 13:10 UTC, huxiaoman7 requested changes
文末我新增了一点，让大家有疑问也可添加微信小助手和QQ群

2021-03-25 00:46 UTC, leonwanghui commented on docs/zh_CN/source/community/contributing.md
> +- 对于错误修复PR，请确保所有相关问题都已链接。
这个只是社区贡献文档，你说的这个最好放到communication.md里面

2021-03-25 09:54 UTC, hannibalhuang commented on docs/en/source/community/contributing.md
> +    git remote add upstream https://github.com/tinyms-ai/tinyms.git
git remote -u should be enough

2021-03-25 09:55 UTC, hannibalhuang commented on docs/en/source/community/contributing.md
> +    To avoid inconsistency between multiple branches, checking out to a new branch for every pull request is `SUGGESTED`:
please enter a blank for code blocks to work in markdown

2021-03-25 10:02 UTC, hannibalhuang requested changes
Please update the code block with markdown lint requirement

2021-03-26 01:43 UTC, hannibalhuang approved these changes
LGTM

2021-03-26 02:29 UTC, huxiaoman7 approved these changes

2021-03-26 02:31 UTC, merged