Add install doc
tinyms-ai/tinyms pull request #46
Opened 2021-03-25 11:03 UTC by lyd911

2021-03-25 11:42 UTC, leonwanghui approved these changes
LGTM

2021-03-26 01:19 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +For users owning a clean environment, recommend using [pypi](https://pypi.org/) to install TinyMS after satisfy the following prerequisites. For setting up python environment, [Anaconda](https://www.
For users who own a clean environment, it is recommend to use pypi to install TinyMS given that the following requirements are meet

2021-03-26 01:21 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +For users owning a clean environment, recommend using [pypi](https://pypi.org/) to install TinyMS after satisfy the following prerequisites. For setting up python environment, [Anaconda](https://www.
For those who don't, Anaconda is a good choice for setting up the python environment

2021-03-26 01:22 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +Chinese Domestic users recommend running the following code setting the mirror site of pypi to solve the downloading issue
For China based users it is recommended to run ..... to help with faster download

2021-03-26 01:24 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +For users' environment do not want to change the local env which also cannot satisfy the prerequisites, using [docker](https://www.docker.com/) to install is recommended
For those who don't want to affect the local develop environment due to difficulty of meeting the prerequisites

2021-03-26 01:28 UTC, hannibalhuang requested changes
Section titles needs to be modified, a lot of the sentences either lack of subject or not properly composed

2021-03-26 01:28 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +If want to try jupyter, run the following command line
lack of subject, if who ??

2021-03-26 01:28 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
> +## Developer install TinyMS
TinyMS Installation For Experienced Developers

2021-03-26 02:03 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +For users who own a clean environment, it is recommend to use [pypi](https://pypi.org/) to install TinyMS given that the following requirements are meet. For those who don't, [Anaconda](https://www.a
`recommend` or `recommended`?

2021-03-26 02:04 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +If user want to try the tutorials that are written in `.ipynb` files，please pull jupyter version of TinyMS which jupyter component are installed by default
s/want/wants

2021-03-26 02:04 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +If user want to try the tutorials that are written in `.ipynb` files，please pull jupyter version of TinyMS which jupyter component are installed by default
s/which/where

2021-03-26 02:05 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +If user want to try the tutorials that are written in `.ipynb` files，please pull jupyter version of TinyMS which jupyter component are installed by default
s/component/components

2021-03-26 02:05 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +For developers who want to develope based on TinyMS, install from source
s/develope/develop

2021-03-26 02:06 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +git clone https:github.com/tinyms-ai/tinyms.git
The link should be `https://github.com/tinyms-ai/tinyms.gi`

2021-03-26 02:07 UTC, leonwanghui requested changes

2021-03-26 02:07 UTC, leonwanghui commented on docs/zh_CN/source/quickstart/install.md
> +git clone https:github.com/tinyms-ai/tinyms.git
Same comments

2021-03-26 02:12 UTC, hannibalhuang requested changes
nixes for section titles

2021-03-26 02:12 UTC, hannibalhuang commented on docs/en/source/quickstart/install.md
## Installation For Beginners

2021-03-26 03:11 UTC, leonwanghui commented on docs/en/source/quickstart/install.md
> +## TinyMS Installation For Experienced Developers
Please remove `TinyMS`

2021-03-26 03:28 UTC, leonwanghui approved these changes
LGTM

2021-03-26 06:16 UTC, hannibalhuang approved these changes
LGTM

2021-03-26 06:29 UTC, merged